source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               bin/,\
               build.properties,\
               contexts.xml,\
               OSGI-INF/,\
               OSGI-INF/l10n/bundle.properties,\
               icons/,\
               lib/
src.includes = lib/,\
               icons/
